name: Build and Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flit
        sudo apt-get install build-essential cmake

    - name: Build IQ-TREE
      run: |
        git clone --branch libiqtree https://github.com/iqtree/iqtree2.git
        cd iqtree2
        mkdir build && cd build
        cmake -DBUILD_LIB=ON ..
        make -j$(nproc)
        sudo make install

    - name: Build and install the library
      run: |
        flit build
        flit install

    - name: Run tests
      run: |
        pip install pytest
        pytest tests
