name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
        conda create -n c312 python=3.12 -y
        echo "source activate c312" >> ~/.bashrc
        source activate c312
        pip install pybind11 pytest

    - name: Build IQTree shared library
      run: |
        git clone https://github.com/iqtree/iqtree2/
        cd iqtree2
        git checkout libiqtree
        mkdir build && cd build
        cmake -DBUILD_LIB=ON ..
        make -j

    - name: Build and install pyiqtree
      run: |
        cd pyiqtree
        python setup.py install

    - name: Run tests
      run: |
        pytest tests
