name: Build IQ-TREE Static Library

on: [workflow_dispatch]

jobs:
  tests:
    name: Run static IQ-TREE library for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14] # Intel linux, Intel Mac, ARM Mac

    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
          submodules: "recursive"
      
    #   - name: Build IQ-TREE
    #     run: |
    #       if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
    #         sudo ./build_tools/before_all_linux.sh
    #       else
    #         ./build_tools/before_all_mac.sh
    #       fi
      - name: Mock Build
        run: echo "hi" > tmp.txt
    
      - uses: actions/upload-artifact@v4
        with:
            name: ${{matrix.os}}-tmp
            path: tmp.txt
            if-no-files-found: error
            retention-days: 1
            overwrite: true
