name: Build IQ-TREE Static Library

on: 
  workflow_dispatch:
  schedule:
    - cron: '35 4 1 * *' # Every 1st day of the month.
  push:
    paths: iqtree2

jobs:
  tests:
    name: Run static IQ-TREE library for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14] # Intel linux, Intel Mac, ARM Mac

    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
          submodules: "recursive"
      
      - name: Build IQ-TREE
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo ./build_tools/before_all_linux.sh
          else
            ./build_tools/before_all_mac.sh
          fi
    
      - uses: actions/upload-artifact@v4
        with:
            name: ${{matrix.os}}-libiqtree2.a
            path: src/piqtree2/libiqtree/libiqtree2.a
            if-no-files-found: error
            retention-days: 90
            overwrite: true
