name: Build

on: [workflow_dispatch]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        # os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        os: [ubuntu-latest, macos-13, macos-14]

    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.1
        env: # Can specify per os - e.g. CIBW_BEFORE_ALL_LINUX, CIBW_BEFORE_ALL_MACOS, CIBW_BEFORE_ALL_WINDOWS 
          CIBW_BEFORE_ALL_LINUX: ./build_tools/before_all_linux.sh
          CIBW_BEFORE_ALL_MACOS: ./build_tools/before_all_mac.sh
          CIBW_SKIP: "*_i686"
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {package}/tests

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
